language: android

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - android-29
    - android-30
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
jdk:
   - openjdk11

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - $HOME/.gradle/nodejs/
 - node_modules

before_install:
  - "pip install urllib3[secure]"
  - "pip install codecov"

script:
   - travis_wait 60 ./gradlew clean jacocoTestReport sonarqube
   
after_success:
  - "codecov"

sudo: false
